# -*- coding: utf-8 -*-
"""Multimodal GenAI Application.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RhldvkTmN39Qg2Wa_eQ9b3ZrzGZA6JZP
"""

!pip install transformers
!pip install torch
!pip install pillow

import torch
from PIL import Image
from transformers import BlipProcessor, BlipForQuestionAnswering

processor = BlipProcessor.from_pretrained("Salesforce/blip-vqa-base")
model = BlipForQuestionAnswering.from_pretrained("Salesforce/blip-vqa-base")

print("VQA Model loaded successfully!")

from google.colab import files
uploaded = files.upload()

image = Image.open(list(uploaded.keys())[0]).convert("RGB")
image

question = "What is happening in this image?"

inputs = processor(image, question, return_tensors="pt")

out = model.generate(**inputs)

answer = processor.decode(out[0], skip_special_tokens=True)

print("Final Answer:", answer)

